name: Deploy Vanilla JS (NPM) Sample

on:
  push:
    branches: ["main"]
    paths:
      - 'web-sdk-samples/cortexscan-sample_vanillajs_app_with_npm_package_import/**'
      - '.github/workflows/deploy-cortexscan-vanilla-npm.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install Dependencies
        working-directory: ./web-sdk-samples/cortexscan-sample_vanillajs_app_with_npm_package_import
        run: npm ci

      - name: Build Webpack App
        working-directory: ./web-sdk-samples/cortexscan-sample_vanillajs_app_with_npm_package_import
        # This runs "webpack --mode production"
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: web-sdk-samples/cortexscan-sample_vanillajs_app_with_npm_package_import/dist
          target-folder: cortexscan-sample_vanillajs_app_with_npm_package_import
          clean: false